const jCategory = [
    {
        index:0,
        image:"../images/google.png",
        title: "Web Developer",
        rate: '$900-1200/m',
        av: "Full Time",
        companyName: "Google",
        location: "Nairobi",
        vacancy: "01",
        hours: "40h/ Week",
        description: "Google's software engineers develop the next-generation technologies that change how billions of users connect, explore, and interact with information and one another. Our products need to handle information at massive scale, and extend well beyond web search. We're looking for engineers who bring fresh ideas from all areas, including information retrieval, distributed computing, large-scale system design, networking and data storage, security, artificial intelligence, natural language processing, UI design and mobile; the list goes on and is growing every day. As a software engineer, you will work on a specific project critical to Google’s needs with opportunities to switch teams and projects as you and our fast-paced business grow and evolve. We need our engineers to be versatile, display leadership qualities and be enthusiastic to take on new problems across the full-stack as we continue to push technology forward.",
        workplace: "Hybrid",
        education: "Bachelor's degree in Computer Science or related technical field.",
        experience: "2 years"
    },
    {
        index:1,
        image:"../images/uber.png",
        title: "Freelancer",
        rate: '$800-1000/m',
        av: "Freelancer",
        companyName: "Uber",
        location: "USA",
        vacancy: "10",
        hours: "50h/ Week",
        description: "We're looking for engineers who bring fresh ideas from all areas, including information retrieval, distributed computing, large-scale system design, networking and data storage, security, artificial intelligence, natural language processing, UI design and mobile; the list goes on and is growing every day. As a software engineer, you will work on a specific project critical to Google’s needs with opportunities to switch teams and projects as you and our fast-paced business grow and evolve. We need our engineers to be versatile, display leadership qualities and be enthusiastic to take on new problems across the full-stack as we continue to push technology forward.",
        workplace: "Work from home",
        education: "Bachelor's degree in Computer Science or related technical field.",
        experience: "1 year"
    },
    {
        index:2,
        image:"../images/linkedin.png",
        title: "Data Scientist",
        rate: '$1200/m',
        av: "Part Time",
        companyName: "LinkedIn",
        location: "USA",
        vacancy: "1",
        hours: "50h/ Week",
        description: "We're looking for engineers who bring fresh ideas from all areas, including information retrieval, distributed computing, large-scale system design, networking and data storage, security, artificial intelligence, natural language processing, UI design and mobile; the list goes on and is growing every day. As a software engineer, you will work on a specific project critical to Google’s needs with opportunities to switch teams and projects as you and our fast-paced business grow and evolve. We need our engineers to be versatile, display leadership qualities and be enthusiastic to take on new problems across the full-stack as we continue to push technology forward.",
        workplace: "Work from home",
        education: "Bachelor's degree in Computer Science or related technical field.",
        experience: "1 years"
    },
    {
        index:3,
        image:"../images/facebook.png",
        title: "UX/UI Designer",
        rate: '$800/m',
        av: "Part Time",
        companyName: "Meta",
        location: "USA",
        vacancy: "1",
        hours: "30h/ Week",
        description: "We're looking for engineers who bring fresh ideas from all areas, including information retrieval, distributed computing, large-scale system design, networking and data storage, security, artificial intelligence, natural language processing, UI design and mobile; the list goes on and is growing every day. As a software engineer, you will work on a specific project critical to Google’s needs with opportunities to switch teams and projects as you and our fast-paced business grow and evolve. We need our engineers to be versatile, display leadership qualities and be enthusiastic to take on new problems across the full-stack as we continue to push technology forward.",
        workplace: "Work from home",
        education: "Bachelor's degree in Computer Science or related technical field.",
        experience: "1 year"
    },
    {
        index:4,
        image:"../images/apple.png",
        title: "Web Developer",
        rate: '$1000/m',
        av: "Full Time",
        companyName: "Apple Inc.",
        location: "USA",
        vacancy: "6",
        hours: "50h/ Week",
        description: "We're looking for engineers who bring fresh ideas from all areas, including information retrieval, distributed computing, large-scale system design, networking and data storage, security, artificial intelligence, natural language processing, UI design and mobile; the list goes on and is growing every day. As a software engineer, you will work on a specific project critical to Google’s needs with opportunities to switch teams and projects as you and our fast-paced business grow and evolve. We need our engineers to be versatile, display leadership qualities and be enthusiastic to take on new problems across the full-stack as we continue to push technology forward.",
        workplace: "Work from home",
        education: "Bachelor's degree in Computer Science or related technical field.",
        experience: "3 years"
    },
    {
        index:5,
        image:"../images/instagram.png",
        title: "Product Design",
        rate: '$1000/m',
        av: "Part Time",
        companyName: "Meta",
        location: "USA",
        vacancy: "10",
        hours: "30h/ Week",
        description: "We're looking for engineers who bring fresh ideas from all areas, including information retrieval, distributed computing, large-scale system design, networking and data storage, security, artificial intelligence, natural language processing, UI design and mobile; the list goes on and is growing every day. As a software engineer, you will work on a specific project critical to Google’s needs with opportunities to switch teams and projects as you and our fast-paced business grow and evolve. We need our engineers to be versatile, display leadership qualities and be enthusiastic to take on new problems across the full-stack as we continue to push technology forward.",
        workplace: "Work from home",
        education: "Bachelor's degree in Computer Science or related technical field.",
        experience: "2 years"
    },
    {
        index:6,
        image:"../images/wordpress.png",
        title: "Freelancer",
        rate: '$1000/m',
        av: "Freelancer",
        companyName: "Wordpress",
        location: "USA",
        vacancy: "10",
        hours: "40h/ Week",
        description: "We're looking for engineers who bring fresh ideas from all areas, including information retrieval, distributed computing, large-scale system design, networking and data storage, security, artificial intelligence, natural language processing, UI design and mobile; the list goes on and is growing every day. As a software engineer, you will work on a specific project critical to Google’s needs with opportunities to switch teams and projects as you and our fast-paced business grow and evolve. We need our engineers to be versatile, display leadership qualities and be enthusiastic to take on new problems across the full-stack as we continue to push technology forward.",
        workplace: "Work from home",
        education: "Bachelor's degree in Computer Science or related technical field.",
        experience: "2 years"
    },
];